apiVersion: v1
kind: Service

metadata:
  name: my-app-frontend-lb

spec:
  selector:
    app: my-app-frontend
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
  LoadBalancerIP: 192.168.101.105